version: '3'

services:
  main:
    container_name: admin_front_main
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: ghcr.io/ArturW1998/admin-dashboard/main:latest
    ports:
      - "${ADMIN_BACK_IP}:8000:80"

networks:
  admin:
    driver: bridge
